package Pojo;
// Generated 17-abr-2017 13:20:06 by Hibernate Tools 4.3.1



/**
 * Votante generated by hbm2java
 */
public class Votante  implements java.io.Serializable {


     private Integer idVotante;
     private String nif;
     private byte[] pass;
     private String votado;

    public Votante() {
    }

    public Votante(String nif, byte[] pass, String votado) {
       this.nif = nif;
       this.pass = pass;
       this.votado = votado;
    }
    
    public Votante(String nif, String pass, String votado) {
       this.nif = nif;
       this.pass = pass.getBytes();
       this.votado = votado;
    }
    
    public Votante(String nif, String pass) {
       this.nif = nif;
       this.pass = pass.getBytes();
    }
   
    public Integer getIdVotante() {
        return this.idVotante;
    }
    
    public void setIdVotante(Integer idVotante) {
        this.idVotante = idVotante;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public byte[] getPass() {
        return this.pass;
    }
    
    public void setPass(byte[] pass) {
        this.pass = pass;
    }
    public void setPass(String pass) {
        this.pass = pass.getBytes();
    }
    public String getVotado() {
        return this.votado;
    }
    
    public void setVotado(String votado) {
        this.votado = votado;
    }




}


